version: '3.8'
services:
  db:
    container_name: oauthdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oauthdb
    ports:
      - "5432:5432"