apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  replicas: 1
  template:
    metadata:
      labels:
        app: oauth
        version: v1
    spec:
      containers:
        - name: oauth
          env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom -Dspring.profiles.active=prod
            - name: DB_SERVER
              value: 
            - name: DB_USERNAME
              value: 
            - name: DB_PASSWORD
              value: 
          image: diegoazd/oauth:2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    app: oauth
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: oauth
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: oauth-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth
spec:
  hosts:
    - "*"
  gateways:
    - oauth-gateway
  http:
    - match:
        - uri:
            prefix: /oauth
      route:
        - destination:
            port:
              number: 8080
            host: oauth
